### ISSUE TITLE
Separate auctionStarts to make price oracle more powerful

### ISSUE THREAD

**Issue by dteiml** [gnosis/dx-contracts#63]
Currently, we overwrite auctionStarts every time a new auction is scheduled, and we also use it as a flag if the auction pair is paused/waiting. This does not lead to a very good price oracle for multiple reasons: 1. we wouldn't know when auctions started to tell if the price is reliable, 2. we wouldn't be able to find historical prices.

Instead auctionStarts should not be overwritten. Additionally, add a `mapping (address => mapping (address => bool)) isWaiting` that will store that flag. Refactor code so it meets specifications. 

Finally, update the documentation.

**Comment by anxolin** [comment]
Thanks Dom!

The problem I see is:
- The date used for the trade price should be the closing date, not the start date. So the closing date is more suitable for price oracles
- If we do this, we need to fix the tests first: 96 tests
- Is not backward compatible, we need to adapt bots, scripts, api, cli and web. We are low on capacity right now.

Maybe we could do another approach were we just add the closing date, so is backward compatible and we have a better date. We still have problem with the date for close theoreticals, but maybe we can try to find a solution so we get the actual closing date instead of the clearing date.

What do you think?

**Comment by dasanra** [comment]
Related pull request is merged, so I assume this issue can be closed
